# Generated by Django 3.0.3 on 2020-04-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseasetables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='d',
            field=models.CharField(default='diabetes', max_length=30),
        ),
    ]
