# Generated by Django 3.0.3 on 2020-04-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('birthday', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('qualification', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('specialized', models.CharField(max_length=30)),
                ('experience', models.CharField(max_length=30)),
                ('license', models.CharField(max_length=30)),
                ('hospital', models.CharField(max_length=30)),
                ('fee', models.IntegerField()),
                ('res_code', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
                ('password', models.IntegerField()),
            ],
        ),
    ]
