# Generated by Django 3.0.3 on 2020-04-11 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_patients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='patients',
            new_name='patient',
        ),
    ]
