# Generated by Django 3.0.3 on 2020-04-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200411_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='ph_no',
            field=models.IntegerField(),
        ),
    ]
