# Generated by Django 3.0.3 on 2020-04-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20200411_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data1',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
