# Generated by Django 3.0.3 on 2020-04-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20200411_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data1',
            name='fee',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data1',
            name='res_code',
            field=models.IntegerField(),
        ),
    ]
