# Generated by Django 3.0.3 on 2020-05-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20200427_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data1',
            name='fee',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='data1',
            name='res_code',
            field=models.CharField(max_length=10),
        ),
    ]
