# Generated by Django 3.0.3 on 2020-05-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20200506_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='data1',
            name='profilePicture',
            field=models.ImageField(default='hlo', upload_to='pics'),
        ),
    ]
