# Generated by Django 3.0.3 on 2020-05-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_data1_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data1',
            name='profilePicture',
            field=models.ImageField(default='hlo', upload_to='media'),
        ),
    ]
