# Generated by Django 3.0.3 on 2020-05-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20200508_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data1',
            name='profilePicture',
            field=models.ImageField(default='hlo', upload_to=''),
        ),
    ]
