# Generated by Django 3.0.3 on 2020-05-13 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20200508_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='data1',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='webapp.data1'),
        ),
    ]
