# Generated by Django 3.0.3 on 2020-05-13 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_patient_data1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='data1',
        ),
        migrations.AddField(
            model_name='patient',
            name='dr_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.data1'),
        ),
    ]
