# Generated by Django 3.0.3 on 2020-05-13 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20200513_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='dr_name',
            new_name='data1',
        ),
    ]
