# Generated by Django 3.0.3 on 2020-05-13 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_auto_20200513_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='date_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.DateField()),
                ('time', models.TimeField()),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.patient')),
            ],
        ),
    ]
