# Generated by Django 3.0.3 on 2020-05-13 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date_time',
            name='patient_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.patient'),
        ),
    ]
