# Generated by Django 3.0.3 on 2020-05-13 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_auto_20200513_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date_time',
            name='patient_name',
        ),
    ]
