# Generated by Django 3.0.3 on 2020-05-14 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_remove_date_time_patient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dr_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.data1'),
        ),
    ]
