# Generated by Django 3.0.3 on 2020-05-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_auto_20200516_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merge',
            name='patient_name',
        ),
        migrations.AddField(
            model_name='merge',
            name='doctor_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='merge',
            name='dr_username',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='merge',
            name='patient_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='merge',
            name='dr_name',
            field=models.CharField(max_length=30),
        ),
    ]
