# Generated by Django 2.2.12 on 2020-05-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_auto_20200517_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='ph_no',
            field=models.CharField(max_length=14),
        ),
    ]
