# Generated by Django 3.0.3 on 2020-05-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_auto_20200518_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='merge',
            name='p_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
