# Generated by Django 3.0.3 on 2020-05-22 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0027_auto_20200522_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merge',
            name='p_name',
        ),
    ]
