# Generated by Django 3.0.3 on 2020-05-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_remove_merge_p_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='merge',
            name='p_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
